species:
  - "AAUR"
  - "ACER"
  - "ADOR"
  - "AFUL"
  - "AMEL"
  - "APLU"
  - "APUR"
  - "AVIR"
  - "BAFF"
  - "BTER"
  - "CCAL"
  - "CGIG"
  - "DNOV"
  - "EMEX"
  - "FVAR"
  - "HANT"
  - "HLAB"
  - "HLIG"
  - "HQUA"
  - "HVOL"
  - "LFIG"
  - "LLAT"
  - "LLEU"
  - "LMAR"
  - "LMOR"
  - "LOEN"
  - "LPAU"
  - "LVIE"
  - "LZEP"
  - "MBIC"
  - "MEUR"
  - "MROT"
  - "NFAB"
  - "NFLA"
  - "NMEL"
  - "OBIC"
  - "OLIG"
  - "SMON"
  - "SPHA"
  - "STUM"
  - "TDIV"
  - "XVIO"

paths:
  working_dir: "/pscratch/bmjo263_uksr/SAV_TFBS"
  motifs: "/pscratch/bmjo263_uksr/TFBS_project/JASPAR2024_CORE_insects_non-redundant_pfms_jaspar_ALL/{motif}.jaspar"
  gffs: "gffs/{sample}.gff3"
  longest_isoforms: "longest_isoforms/{sample}_longiso.gff3"
  longest_peps: "longest_peps/{sample}_longpeps.fa"

  chrom_lengths: "genomes/{sample}_chrom_lengths.txt"
  pep_beds: "pep_beds/{sample}.bed"
  promoter_beds: "promoter_beds/{sample}.bed"
  species_peptide_pairs: "species_peptide_list.txt"
  genomes: "genomes/{sample}_genome.fa"
  bg_comp: "bg_tabs/{sample}_bg_tab.comp"

  pep_fastas: "pep_genomes/{sample}_peps.fa"
  promoter_fastas: "promoter_fastas/{sample}_promoters.fa"
  genome_bwt_indices: "genomes/{sample}_genome.fa.1.ebwt"
  pep_bwt_indices: "pep_genomes/{sample}_peps.fa.1.ebwt"
  promoter_bwt_indices: "promoter_genomes/{sample}_promoters.fa.1.ebwt"

  ill_motifs: "PWM_setup/{sample}_output/{motif}.ill"
  score: "PWM_setup/{sample}_output/{motif}.ill.score"
  mba: "PWM_setup/{sample}_output/{motif}.dat"
  tag_list: "PWM_setup/{sample}_output/{motif}_taglist.fa"
  genome_tags: "PWM_results_genome/{sample}/{motif}_bowtie.out"
  pep_tags: "PWM_results_peps/{sample}/{motif}_bowtie.out"
  promoter_tags: "PWM_results_promoter/{sample}/{motif}_bowtie.out"

  genome_species_tables: "PWM_results_genome/{sample}_output_table.txt"
  species_tables: "PWM_results_promoter/{sample}_output_table.txt"

  score_tables: "PWM_results_promoter/motif_scores/{motif}_scores.out"
  count_tables: "PWM_results_promoter/motif_counts/{motif}_counts.out"
  totalcount_tables: "PWM_results_promoter/motif_totalcounts/{motif}_totalcounts.out"

  PGLS_results: "PWM_results_promoter/motif_counts/PGLS/results_{motif}.csv"

containers:
  orthofinder: "docker://davidemms/orthofinder:3.0.1b1"
  agat: "docker://quay.io/biocontainers/agat:1.4.1--pl5321hdfd78af_0"
  pwmscan: "docker://sibswiss/pwmscan:1.1.9"
  bowtie: "docker://biocontainers/bowtie:v1.2.2dfsg-4-deb_cv1"
  bedtools: "docker://quay.io/biocontainers/bedtools:2.27.1--h077b44d_9"
  samtools: "docker://quay.io/biocontainers/samtools:0.1.19--h96c455f_13"
